---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hasmissingsvc
  spec:
    template:
      metadata:
        labels:
          app.kubernetes.io/name: Foo
          app.kubernetes.io/instance: Bar
          app.kubernetes.io/component: FooBar
          app.kubernetes.io/part-of: Foo
          app.kubernetes.io/managed-by: Bar
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hassvcwithincorrectlabels
  spec:
    template:
      metadata:
        labels:
          app.kubernetes.io/name: Foo
          app.kubernetes.io/instance: Bar
          app.kubernetes.io/component: FooBar
          app.kubernetes.io/part-of: Foo
          app.kubernetes.io/managed-by: Bar
- apiVersion: v1
  kind: Service
  metadata:
    name: missingselectorlabels
  spec:
    selector:
      app: Foo