---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hasmissingpdb
  spec:
    template:
      metadata:
        labels:
          app.kubernetes.io/name: Foo
          app.kubernetes.io/instance: Bar
          app.kubernetes.io/component: FooBar
          app.kubernetes.io/part-of: Foo
          app.kubernetes.io/managed-by: Bar
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: pdbhasincorrectlabels
  spec:
    template:
      metadata:
        labels:
          app.kubernetes.io/name: Foo
          app.kubernetes.io/instance: Bar
          app.kubernetes.io/component: FooBar
          app.kubernetes.io/part-of: Foo
          app.kubernetes.io/managed-by: Bar
- apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    name: hasincorrectlabelsfordeployment
  spec:
    minAvailable: 2
    selector:
      matchLabels:
        app: Foo