---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hasmissingsvcaccount
  spec:
    serviceAccountName: missing
- apiVersion: v1
  kind: Service
  metadata:
    name: conftestneedsaseconditem